---

- name: Create FreshRSS configuration file
  template:
    src: freshrss-config.php.j2
    dest: /var/www/freshrss-data/config.php
    owner: "root"
    group: "{{ php_fpm_group }}"
    mode: '0640'

- name: Create FreshRSS constant override file
  template:
    src: constants.local.php.j2
    dest: /usr/pkg/share/freshrss/constants.local.php
    owner: "root"
    group: "{{ php_fpm_group }}"
    mode: '0644'

- name: Create FreshRSS default user configuration
  template:
    src: freshrss-user-config.php.j2
    dest: /var/www/freshrss-data/users/_/config.php
    owner: "root"
    group: "{{ php_fpm_group }}"
    mode: '0640'

- name: Setup FreshRSS cron jobs for feed updates
  cron:
    name: "FreshRSS feed update"
    minute: "*/10"
    job: "{{ php_binary }} /usr/pkg/share/freshrss/app/actualize_script.php > /var/log/freshrss/cron.log 2>&1"
    user: "{{ php_fpm_user }}"
  become: true
