---

- name: Create FreshRSS admin user
  freshrss_user:
    username: "{{ freshrss_admin_user }}"
    password: "{{ freshrss_admin_password }}"
    email: "{{ freshrss_admin_email }}"
    state: present
    php_binary: "{{ php_binary }}"
    freshrss_path: "/usr/pkg/share/freshrss"
    become_user: "{{ php_fpm_user }}"
  become: true

