---

- name: Check if FreshRSS admin user config exists
  stat:
    path: "/var/www/freshrss-data/users/{{ freshrss_admin_user }}/config.php"
  register: freshrss_admin_config
  when: not (force_admin_refresh | default(false))

- name: Create FreshRSS admin user
  freshrss_user:
    username: "{{ freshrss_admin_user }}"
    password: "{{ freshrss_admin_password }}"
    email: "{{ freshrss_admin_email }}"
    state: present
    php_binary: "{{ php_binary }}"
    freshrss_path: "/usr/pkg/share/freshrss"
    become_user: "{{ php_fpm_user }}"
  become: true
  when: (force_admin_refresh | default(false)) or not freshrss_admin_config.stat.exists

