---
- name: Install PHP build dependencies
  community.general.pkgin:
    name: "{{ php_packages }}"
    state: present

- name: Build and install PHP from pkgsrc
  command: make install
  args:
    chdir: /usr/pkgsrc/lang/php83
    creates: /usr/pkg/bin/php83
  become: true

- name: Build and install PHP-FPM from pkgsrc
  command: make install
  args:
    chdir: /usr/pkgsrc/www/php-fpm
    creates: /usr/pkg/sbin/php-fpm83
  become: true

- name: Build and install PHP-PDO from pkgsrc
  command: make install
  args:
    chdir: /usr/pkgsrc/databases/php-pdo_pgsql
    creates: /usr/pkg/include/php/8.3/ext/pdo/php_pdo.h
  become: true

- name: Install php_fpm83 init script
  ansible.builtin.copy:
    src: /usr/pkg/share/examples/rc.d/php_fpm83
    dest: /etc/rc.d/php_fpm83
    owner: root
    group: wheel
    mode: '0755'
    remote_src: true
    force: false

- name: Configure PHP-FPM pool
  template:
    src: php-fpm-pool.conf.j2
    dest: /usr/pkg/etc/php-fpm.d/www.conf
    owner: root
    group: wheel
    mode: '0644'
  notify: restart php-fpm

- name: Configure PHP settings
  template:
    src: php.ini.j2
    dest: /usr/pkg/etc/php.ini
    owner: root
    group: wheel
    mode: '0644'
  notify: restart php-fpm

- name: Add nginx user to www group
  user:
    name: nginx
    groups: www
    append: yes

- name: Start & Enable PHP-FPM service
  ansible.builtin.service:
    name: php_fpm83
    state: started
    enabled: true
  become: true


