---
- name: Install PHP build dependencies
  community.general.pkgin:
    name: "{{ php_packages }}"
    state: present

- name: Build and install PHP from pkgsrc
  command: make install
  args:
    chdir: "{{ php_pkgsrc_dir }}"
    creates: "{{ php_binary }}"
  become: true

- name: Build and install PHP-FPM from pkgsrc
  command: make install
  args:
    chdir: /usr/pkgsrc/www/php-fpm
    creates: "{{ php_fpm_binary }}"
  become: true

- name: Build and install PHP-PDO from pkgsrc
  command: make install
  args:
    chdir: /usr/pkgsrc/databases/php-pdo
    creates: "{{ php_config_dir }}/pdo.ini"
  become: true

- name: Build and install PHP-PDO from pkgsrc
  command: make install
  args:
    chdir: /usr/pkgsrc/databases/php-pdo_pgsql
    creates: "{{ php_etc_dir }}/php.d/pdo_pgsql.ini"
  become: true

- name: Build and install PHP-INT from pkgsrc
  command: make install
  args:
    chdir: /usr/pkgsrc/textproc/php-intl
    creates: "{{ php_config_dir }}/intl.ini"
  become: true

- name: Install FreshRSS build dependencies
  community.general.pkgin:
    name:
      - meson
      - curl
      - cmake
      - bison
      - re2c
      - libzip
    state: present

- name: Build and install php-curl
  command: make install
  args:
    chdir: /usr/pkgsrc/www/php-curl/
    creates: "{{ php_config_dir }}/curl.ini"
  become: true

- name: Install {{ php_fpm_service }} init script
  ansible.builtin.copy:
    src: "/usr/pkg/share/examples/rc.d/{{ php_fpm_service }}"
    dest: "/etc/rc.d/{{ php_fpm_service }}"
    owner: root
    group: wheel
    mode: '0755'
    remote_src: true
    force: false

- name: Configure PHP-FPM pool
  template:
    src: php-fpm-pool.conf.j2
    dest: /usr/pkg/etc/php-fpm.d/www.conf
    owner: root
    group: wheel
    mode: '0644'
  notify: restart php-fpm

- name: Configure PHP settings
  template:
    src: php.ini.j2
    dest: /usr/pkg/etc/php.ini
    owner: root
    group: wheel
    mode: '0644'
  notify: restart php-fpm

- name: Add nginx user to www group
  user:
    name: nginx
    groups: www
    append: yes

- name: Start & Enable PHP-FPM service
  ansible.builtin.service:
    name: "{{ php_fpm_service }}"
    state: started
    enabled: true
  become: true


