---
- name: NetBSD Server Setup
  hosts: all
  become: true
  vars:
    # PHP version configuration
    php_version_major: "8"
    php_version_minor: "3"
    php_version_full: "{{ php_version_major }}.{{ php_version_minor }}"
    php_version_short: "{{ php_version_major }}{{ php_version_minor }}"
    # Python version configuration
    python_version_major: "3"
    python_version_minor: "12"
    python_version_full: "{{ python_version_major }}.{{ python_version_minor }}"
    python_version_short: "{{ python_version_major }}{{ python_version_minor }}"
    # PostgreSQL version configuration
    postgresql_version_major: "16"
  roles:
    - { role: os-release, tags: ["system", "os-release"] }
    - { role: netbsd-pkgin, tags: ["system", "netbsd-pkgin"] }
    - { role: netbsd-pkgsrc, tags: ["system", "netbsd-pkgsrc"] }
    - { role: netbsd-python, tags: ["system", "netbsd-python"] }
    - { role: vim, tags: ["system", "vim"] }
    - { role: zsh, tags: ["system", "zsh"] }
    - { role: netbsd-misc-packages, tags: ["system", "netbsd-misc-packages"] }
    - { role: netbsd-mdns, tags: ["system", "netbsd-mdns"] }
    - role: netbsd-nginx
      tags: ["service", "netbsd-nginx"]
      vars:
        static_sites:
          - name: "lens"
            domain: "lens.kakwalab.ovh"
            root: "/var/www/lens"
            index: "index.html"
          - name: "sun"
            domain: "sun.kakwalab.ovh"
            root: "/var/www/sun"
            index: "index.html"
          - name: "netbsd"
            domain: "netbsd.kakwalab.ovh"
            root: "/var/www/netbsd"
            autoindex: true
            index: ""
        reverse_proxies:
          - name: "voron0"
            domain: "voron0.kakwalab.ovh"
            upstream: "https://192.168.1.92/"
            ssl_verify: false
            auth_enabled: true
            auth_user: "kakwa"
            auth_password: "{{ vault_proxy_password | default(lookup('password', './proxy.password.txt chars=ascii_letters,digits length=16')) }}"
          - name: "ender3"
            domain: "ender3.kakwalab.ovh"
            upstream: "https://192.168.1.27/"
            ssl_verify: false
            auth_enabled: true
            auth_user: "kakwa"
            auth_password: "{{ vault_proxy_password | default(lookup('password', './proxy.password.txt chars=ascii_letters,digits length=16')) }}"
          - name: "rockrobo"
            domain: "rockrobo.kakwalab.ovh"
            upstream: "http://192.168.1.37/"
            ssl_verify: true
            auth_enabled: true
            auth_user: "kakwa"
            auth_password: "{{ vault_proxy_password | default(lookup('password', './proxy.password.txt chars=ascii_letters,digits length=16')) }}"
    - role: netbsd-postgresql
      tags: ["service", "netbsd-postgresql"]
      vars:
        postgresql_databases:
          - name: "freshrss"
            user: "freshrss"
            password: "{{ vault_dbfreshrss_password | default(lookup('password', './freshrss_db.password.txt chars=ascii_letters,digits length=16')) }}"
    - role: netbsd-php
      tags: ["app", "netbsd-php"]
    - role: netbsd-freshrss
      tags: ["app", "netbsd-freshrss"]
      vars:
        basic_auth_enabled: false
        freshrss_domain: "rss.kakwalab.ovh"
        freshrss_db_name: "freshrss"
        freshrss_db_user: "freshrss"
        freshrss_db_password: "{{ vault_dbfreshrss_password | default(lookup('password', './freshrss_db.password.txt chars=ascii_letters,digits length=16')) }}"
        freshrss_admin_user: "kakwa"
        freshrss_admin_password: "{{ vault_proxy_password | default(lookup('password', './proxy.password.txt chars=ascii_letters,digits length=16')) }}"
        freshrss_admin_email: "admin@kakwalab.ovh"
        freshrss_auth_user: "kakwa"
        freshrss_auth_password: "{{ vault_proxy_password | default(lookup('password', './proxy.password.txt chars=ascii_letters,digits length=16')) }}"
