---
- name: NetBSD Server Setup
  hosts: all
  become: true
  vars:
    # PHP version configuration
    php_version_major: "8"
    php_version_minor: "3"
    php_version_full: "{{ php_version_major }}.{{ php_version_minor }}"
    php_version_short: "{{ php_version_major }}{{ php_version_minor }}"
  roles:
    - os-release
    - netbsd-pkgin
    - netbsd-pkgsrc
    - vim
    - zsh
    - netbsd-misc-packages
    - netbsd-mdns
    - role: netbsd-nginx
      vars:
        static_sites:
          - name: "mysite"
            domain: "www.example.com"
            root: "/var/www/mysite"
            index: "index.html"
        reverse_proxies:
          - name: "myapp"
            domain: "app.example.com"
            upstream: "http://192.168.1.100:8080/"
            ssl_verify: false
            auth_enabled: true
            auth_user: "admin"
            auth_password: "{{ vault_proxy_password | default(lookup('password', './proxy.password.txt chars=ascii_letters,digits length=16')) }}"
    - role: netbsd-postgresql
      vars:
        postgresql_databases:
          - name: "freshrss"
            user: "freshrss"
            password: "{{ vault_dbfreshrss_password | default(lookup('password', './freshrss_db.password.txt chars=ascii_letters,digits length=16')) }}"
    - role: netbsd-php
    - role: netbsd-freshrss
      vars:
        freshrss_domain: "rss.example.com"
        freshrss_db_name: "freshrss"
        freshrss_db_user: "freshrss"
        freshrss_db_password: "{{ vault_dbfreshrss_password | default(lookup('password', './freshrss_db.password.txt chars=ascii_letters,digits length=16')) }}"
        freshrss_admin_user: "admin"
        freshrss_admin_password: "{{ vault_proxy_password | default(lookup('password', './proxy.password.txt chars=ascii_letters,digits length=16')) }}"
        freshrss_admin_email: "admin@example.com"
        freshrss_auth_user: "admin"
        freshrss_auth_password: "{{ vault_proxy_password | default(lookup('password', './proxy.password.txt chars=ascii_letters,digits length=16')) }}"
