---
- name: NetBSD Server Setup
  hosts: all
  become: true
  vars:
    # PHP version configuration
    php_version_major: "8"
    php_version_minor: "3"
    php_version_full: "{{ php_version_major }}.{{ php_version_minor }}"
    php_version_short: "{{ php_version_major }}{{ php_version_minor }}"
    # Python version configuration
    python_version_major: "3"
    python_version_minor: "12"
    python_version_full: "{{ python_version_major }}.{{ python_version_minor }}"
    python_version_short: "{{ python_version_major }}{{ python_version_minor }}"
  roles:
    - { role: os-release, tags: ["system", "os-release"] }
    - { role: netbsd-pkgin, tags: ["system", "netbsd-pkgin"] }
    - { role: netbsd-pkgsrc, tags: ["system", "netbsd-pkgsrc"] }
    - { role: netbsd-python, tags: ["system", "netbsd-python"] }
    - { role: vim, tags: ["system", "vim"] }
    - { role: zsh, tags: ["system", "zsh"] }
    - { role: netbsd-misc-packages, tags: ["system", "netbsd-misc-packages"] }
    - { role: netbsd-mdns, tags: ["system", "netbsd-mdns"] }
    - role: netbsd-nginx
      tags: ["service", "netbsd-nginx"]
      vars:
        static_sites:
          - name: "mysite"
            domain: "www.example.com"
            root: "/var/www/mysite"
            index: "index.html"
        reverse_proxies:
          - name: "myapp"
            domain: "app.example.com"
            upstream: "http://192.168.1.100:8080/"
            ssl_verify: false
            auth_enabled: true
            auth_user: "admin"
            auth_password: "{{ vault_proxy_password | default(lookup('password', './proxy.password.txt chars=ascii_letters,digits length=16')) }}"
    - role: netbsd-postgresql
      tags: ["service", "netbsd-postgresql"]
      vars:
        postgresql_databases:
          - name: "freshrss"
            user: "freshrss"
            password: "{{ vault_dbfreshrss_password | default(lookup('password', './freshrss_db.password.txt chars=ascii_letters,digits length=16')) }}"
    - role: netbsd-php
      tags: ["app", "netbsd-php"]
    - role: netbsd-freshrss
      tags: ["app", "netbsd-freshrss"]
      vars:
        freshrss_domain: "rss.example.com"
        freshrss_db_name: "freshrss"
        freshrss_db_user: "freshrss"
        freshrss_db_password: "{{ vault_dbfreshrss_password | default(lookup('password', './freshrss_db.password.txt chars=ascii_letters,digits length=16')) }}"
        freshrss_admin_user: "admin"
        freshrss_admin_password: "{{ vault_proxy_password | default(lookup('password', './proxy.password.txt chars=ascii_letters,digits length=16')) }}"
        freshrss_admin_email: "admin@example.com"
        freshrss_auth_user: "admin"
        freshrss_auth_password: "{{ vault_proxy_password | default(lookup('password', './proxy.password.txt chars=ascii_letters,digits length=16')) }}"
