---
- name: NetBSD Sparc Server
  hosts: all
  become: true
  roles:
    - os-release
    - netbsd-pkgin
    - netbsd-pkgsrc
    - vim
    - zsh
    - netbsd-misc-packages
    - netbsd-mdns
    - role: netbsd-nginx
      vars:
        static_sites:
          - name: "lens"
            domain: "lens.kakwalab.ovh"
            root: "/var/www/lens"
            index: "index.html"
          - name: "sun"
            domain: "sun.kakwalab.ovh"
            root: "/var/www/sun"
            index: "index.html"
        reverse_proxies:
          - name: "voron0"
            domain: "voron0.kakwalab.ovh"
            upstream: "https://192.168.1.92/"
            ssl_verify: false
            auth_enabled: true
            auth_user: "kakwa"
            auth_password: "{{ vault_proxy_password | default(lookup('password', './proxy.password.txt chars=ascii_letters,digits length=16')) }}"
          - name: "ender3"
            domain: "ender3.kakwalab.ovh"
            upstream: "https://192.168.1.27/"
            ssl_verify: false
            auth_enabled: true
            auth_user: "kakwa"
            auth_password: "{{ vault_proxy_password | default(lookup('password', './proxy.password.txt chars=ascii_letters,digits length=16')) }}"
          - name: "rockrobo"
            domain: "rockrobo.kakwalab.ovh"
            upstream: "http://192.168.1.27/"
            ssl_verify: true
            auth_enabled: true
            auth_user: "kakwa"
            auth_password: "{{ vault_proxy_password | default(lookup('password', './proxy.password.txt chars=ascii_letters,digits length=16')) }}"
    - role: netbsd-postgresql
      vars:
        postgresql_databases:
          - name: "ttrss"
            user: "ttrss"
            password: "{{ vault_dbttrss_password | default(lookup('password', './ttrss_db.password.txt chars=ascii_letters,digits length=16')) }}"
    - role: netbsd-ttrss
      vars:
        ttrss_domain: "rss.kakwalab.ovh"
        ttrss_db_name: "ttrss"
        ttrss_db_user: "ttrss"
        ttrss_db_password: "{{ vault_dbttrss_password | default(lookup('password', './ttrss_db.password.txt chars=ascii_letters,digits length=16')) }}"
        ttrss_auth_user: "kakwa"
        ttrss_auth_password: "{{ vault_proxy_password | default(lookup('password', './proxy.password.txt chars=ascii_letters,digits length=16')) }}"
