---
# Domain configurations
ttrss_domain: "ttrss.example.com"

# Tiny Tiny RSS configuration
ttrss_admin_user: "admin"
ttrss_admin_password: "{{ vault_ttrss_admin_password | default('admin123') }}"
ttrss_admin_email: "admin@example.com"
ttrss_single_user_mode: false

# Database connection (for TTRSS)
ttrs_db_name: "ttrss"
ttrs_db_user: "ttrss"
ttrs_db_password: "{{ vault_postgresql_password | default('changeme123') }}"
ttrss_db_host: "localhost"
ttrss_db_port: 5432
php_fpm_listen: "/var/run/php-fpm83"
