---
# Domain configurations
ttrss_domain: "ttrss.example.com"

# Tiny Tiny RSS configuration
ttrss_admin_user: "admin"
ttrss_admin_password: "{{ vault_ttrss_admin_password | default('admin123') }}"
ttrss_admin_email: "admin@example.com"
ttrss_single_user_mode: false

# Database connection (for TTRSS)
ttrss_db_name: "ttrss"
ttrss_db_user: "ttrss"
ttrss_db_password: "{{ vault_postgresql_password | default('changeme123') }}"
ttrss_db_host: "localhost"
ttrss_db_port: 5432

# Authentication for nginx htpasswd
ttrss_auth_user: "{{ ttrss_admin_user }}"
ttrss_auth_password: "{{ ttrss_admin_password }}"
php_fpm_listen: "/var/run/php-fpm83"
