---
- name: Create SSL certificates directory
  file:
    path: /usr/pkg/etc/nginx/ssl
    state: directory
    owner: root
    group: nginx
    mode: '0750'

- name: Copy OpenSSL configuration file to nginx SSL directory
  copy:
    src: openssl.cnf
    dest: /usr/pkg/etc/nginx/ssl/openssl.cnf
    owner: root
    group: nginx
    mode: '0644'

- name: Generate self-signed certificate for development
  command: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048
    -keyout /usr/pkg/etc/nginx/ssl/selfsigned.key
    -out /usr/pkg/etc/nginx/ssl/selfsigned.crt
    -subj "/C=US/ST=State/L=City/O=Organization/CN=selfsigned.kakwalab.ovh"
    -config /usr/pkg/etc/nginx/ssl/openssl.cnf
  args:
    creates: /usr/pkg/etc/nginx/ssl/selfsigned.crt

- name: Collect all domains for certificate request
  set_fact:
    all_domains: "{{ ([ttrss_domain] if ttrss_domain is defined else []) + 
                     (static_sites | map(attribute='domain') | list) + 
                     (reverse_proxies | map(attribute='domain') | list) }}"

- name: Request SSL certificates with certbot (production)
  command: >
    /usr/pkg/bin/certbot certonly --nginx
    --email {{ ssl_email }}
    --agree-tos
    --no-eff-email
    --domains {{ all_domains | join(',') }}
    {% if ssl_staging %}--staging{% endif %}
  register: certbot_result
  when: 
    - not ssl_staging
    - all_domains | length > 0
    - letsencrypt_request_enabled | default(false)
  ignore_errors: true

- name: Show certbot production results
  debug:
    msg: "{{ certbot_result.stdout_lines }}"
  when: 
    - not ssl_staging
    - all_domains | length > 0
    - letsencrypt_request_enabled | default(false)
    - certbot_result is defined
- name: Request staging SSL certificates with certbot
  command: >
    /usr/pkg/bin/certbot certonly --nginx
    --email {{ ssl_email }}
    --agree-tos
    --no-eff-email
    --staging
    --domains {{ all_domains | join(',') }}
  register: certbot_staging_result
  when: 
    - ssl_staging
    - all_domains | length > 0
    - letsencrypt_request_enabled | default(false)
  ignore_errors: true

- name: Show certbot staging results
  debug:
    msg: "{{ certbot_staging_result.stdout_lines }}"
  when: 
    - ssl_staging
    - all_domains | length > 0
    - letsencrypt_request_enabled | default(false)
    - certbot_staging_result is defined
