---
- name: "Create htpasswd file for basic authentication (if enabled) for reverse proxy: {{ item.name }}"
  htpasswd:
    path: "/usr/pkg/etc/nginx/.htpasswd.{{ item.name }}"
    name: "{{ item.auth_user }}"
    password: "{{ item.auth_password }}"
    owner: root
    group: nginx
    mode: '0640'
  when: item.auth_enabled | default(false)

- name: "Create reverse proxy nginx configuration for: {{ item.name }}"
  template:
    src: reverse-proxy-nginx.conf.j2
    dest: "/usr/pkg/etc/nginx/sites-available/{{ item.name }}"
    owner: root
    group: wheel
    mode: '0644'
  notify: restart nginx

- name: "Enable reverse proxy site: {{ item.name }}"
  file:
    src: "/usr/pkg/etc/nginx/sites-available/{{ item.name }}"
    dest: "/usr/pkg/etc/nginx/sites-enabled/{{ item.name }}"
    state: link
