---
- name: Check if Let's Encrypt certificates exist for static sites
  stat:
    path: "/usr/pkg/etc/letsencrypt/live/{{ item.domain }}/fullchain.pem"
  register: static_letsencrypt_cert_check
  loop: "{{ static_sites }}"
  when: static_sites is defined

- name: Set use_letsencrypt variable for static sites
  set_fact:
    static_sites: "{{ static_sites | map('combine', {'use_letsencrypt': (static_letsencrypt_cert_check.results | selectattr('item.domain', 'equalto', item.domain) | first).stat.exists | default(false)}) | list }}"
  loop: "{{ static_sites }}"
  when: static_sites is defined

- name: Create static website directories
  file:
    path: "{{ item.root }}"
    state: directory
    owner: root
    group: wheel
    mode: '0755'
  loop: "{{ static_sites }}"
  when: static_sites is defined

- name: Check if index files exist for static sites
  stat:
    path: "{{ item.root }}/{{ item.index }}"
  register: static_index_check
  loop: "{{ static_sites }}"
  when: static_sites is defined

- name: Create default static website index files
  copy:
    content: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>{{ item.item.domain }} - Static Website</title>
          <style>
              body {
                  font-family: Arial, sans-serif;
                  max-width: 800px;
                  margin: 0 auto;
                  padding: 20px;
                  background-color: #f5f5f5;
              }
              .container {
                  background-color: white;
                  padding: 30px;
                  border-radius: 10px;
                  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
              }
              h1 {
                  color: #333;
                  text-align: center;
              }
              p {
                  color: #666;
                  line-height: 1.6;
              }
          </style>
      </head>
      <body>
          <div class="container">
              <h1>Welcome to {{ item.item.domain }}</h1>
              <p>This is a default static website served by nginx. You can replace this content with your own files.</p>
              <p>Upload your HTML, CSS, JavaScript, and other static files to this directory to build your website.</p>
          </div>
      </body>
      </html>
    dest: "{{ item.item.root }}/{{ item.item.index }}"
    owner: root
    group: wheel
    mode: '0644'
  loop: "{{ static_index_check.results }}"
  when: 
    - static_sites is defined
    - not item.stat.exists

- name: Create static website nginx configurations
  template:
    src: static-nginx.conf.j2
    dest: "/usr/pkg/etc/nginx/sites-available/{{ item.name }}"
    owner: root
    group: wheel
    mode: '0644'
  loop: "{{ static_sites }}"
  when: static_sites is defined
  notify: restart nginx

- name: Enable static website sites
  file:
    src: "/usr/pkg/etc/nginx/sites-available/{{ item.name }}"
    dest: "/usr/pkg/etc/nginx/sites-enabled/{{ item.name }}"
    state: link
  loop: "{{ static_sites }}"
  when: static_sites is defined

