---
# Base nginx installation and configuration

- name: Install nginx and certbot packages
  community.general.pkgin:
    name: "{{ nginx_packages }}"
    state: present
  tags:
    - nginx-base

- name: Build and install nginx from pkgsrc
  command: make install
  args:
    chdir: /usr/pkgsrc/www/nginx
    creates: /usr/pkg/sbin/nginx
  become: true
  tags:
    - nginx-base

- name: Install nginx init script
  ansible.builtin.copy:
    src: /usr/pkg/share/examples/rc.d/nginx
    dest: /etc/rc.d/nginx
    owner: root
    group: wheel
    mode: '0755'
    remote_src: true
    force: false
  tags:
    - nginx-base

- name: Configure main nginx configuration
  template:
    src: nginx.conf.j2
    dest: /usr/pkg/etc/nginx/nginx.conf
    owner: root
    group: wheel
    mode: '0644'
  notify: restart nginx
  tags:
    - nginx-base

- name: Create nginx sites-available directory
  file:
    path: /usr/pkg/etc/nginx/sites-available
    state: directory
    owner: root
    group: wheel
    mode: '0755'
  tags:
    - nginx-base

- name: Create nginx sites-enabled directory
  file:
    path: /usr/pkg/etc/nginx/sites-enabled
    state: directory
    owner: root
    group: wheel
    mode: '0755'
  tags:
    - nginx-base
