---
# Python version configuration (can be overridden at playbook level)
python_version_major: "3"
python_version_minor: "12"
python_version_full: "{{ python_version_major }}.{{ python_version_minor }}"
python_version_short: "{{ python_version_major }}{{ python_version_minor }}"

# Derived Python package names
python_binary: "python{{ python_version_short }}"
python_package_prefix: "py{{ python_version_short }}"

# Nginx packages
nginx_packages:
  - nginx
  - "{{ python_package_prefix }}-certbot-nginx"
  - "{{ python_package_prefix }}-passlib"


# SSL configuration
ssl_email: "admin@example.com"
ssl_staging: false

# Static website configurations (empty by default)
static_sites: []

# Reverse proxy configurations (empty by default)
reverse_proxies: []

# Default reverse proxy settings
reverse_proxy_defaults:
  ssl_verify: true  # Set to false to disable SSL certificate verification for HTTPS backends

# Nginx configuration
nginx_worker_processes: "auto"
nginx_worker_connections: 1024
nginx_keepalive_timeout: 65
nginx_client_max_body_size: "100M"

# Security settings
nginx_hide_server_tokens: true
nginx_ssl_protocols: "TLSv1.2 TLSv1.3"
nginx_ssl_ciphers: "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384"
nginx_ssl_prefer_server_ciphers: "on"

# DNS resolution settings for dynamic upstream resolution
# For .local domains (mDNS), include localhost resolver (127.0.0.1)
# This requires the netbsd-mdns role to be configured with unbound forwarding enabled
nginx_dns_resolvers: ["127.0.0.1", "8.8.8.8", "8.8.4.4"]
nginx_dns_valid_time: "10s"  # Shorter cache for .local domains
nginx_dns_timeout: "5s"
nginx_dns_ipv6: false
