---
- name: Enable mdnsd in rc.conf
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: 'mdnsd=YES'
    regexp: '^mdnsd='
    state: present
    backup: yes
  notify: restart mdnsd
  become: true

- name: Add mdnsd to hosts database in nsswitch.conf
  ansible.builtin.replace:
    path: /etc/nsswitch.conf
    regexp: '^(hosts.*files\s+dns)(\s*)$'
    replace: '\1 mdnsd\2'
    backup: yes
  notify: restart mdnsd
  become: true

- name: Start and enable mdnsd service
  ansible.builtin.service:
    name: mdnsd
    state: started
    enabled: true
  become: true

- name: Install packages for mDNS support
  community.general.pkgin:
    name: "{{ mdns_packages }}"
    state: present
  when: mdns_enable_unbound_forwarder or mdns_proxy_enable


- name: Configure unbound for mDNS forwarding
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf
    owner: root
    group: wheel
    mode: '0644'
  notify: restart unbound
  when: mdns_enable_unbound_forwarder

- name: Enable unbound in rc.conf
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: 'unbound=YES'
    regexp: '^unbound='
    state: present
    backup: yes
  notify: restart unbound
  when: mdns_enable_unbound_forwarder

- name: Start and enable unbound service
  ansible.builtin.service:
    name: unbound
    state: started
    enabled: true
  when: mdns_enable_unbound_forwarder

- name: Deploy mDNS proxy script
  ansible.builtin.copy:
    src: mdns-proxy.py
    dest: /usr/pkg/bin/mdns-proxy.py
    owner: root
    group: wheel
    mode: '0755'
  when: mdns_proxy_enable
  notify: restart mdns-proxy
  become: true

- name: Deploy mDNS proxy rc.d script
  ansible.builtin.template:
    src: mdns-proxy.j2
    dest: /etc/rc.d/mdns_proxy
    owner: root
    group: wheel
    mode: '0755'
  when: mdns_proxy_enable
  notify: restart mdns-proxy
  become: true

- name: Enable mDNS proxy in rc.conf
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: 'mdns_proxy_enable=YES'
    regexp: '^mdns_proxy_enable='
    state: present
    backup: yes
  notify: restart mdns-proxy
  when: mdns_proxy_enable
  become: true

- name: Start and enable mDNS proxy service
  ansible.builtin.service:
    name: mdns_proxy
    state: started
    enabled: true
  when: mdns_proxy_enable
  become: true
